server: 
 port: 8888
spring:
 datasource: 
  url: jdbc:mysql://localhost:3306/testdata?characterEncoding=UTF-8
  username: root
  password: 1234
  driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
 
mybatis:
  type-aliases-package: com.primeton.eos.model
  mapper-locations: classpath:mapper/*.xml
  
logging:
  config: classpath:log4j2-spring.xml 
  file: ${spring.application.name}    
  path: ./logs 
  register-shutdown-hook: true      
  
endpoints:
  logfile:
    enabled: true
    external-file: ${logging.path}/${logging.file}-trace.log

eos:
  system-id: eos-system
  service:
    client:
      mode: feign
      http-log-level: basic
      connect-timeout: 10000
      read-timeout: 30000
    server:
      http-log-level: basic
      default-error-status: 500
    security:
      header-secrets:
      - header: X-ER-Gateway-Token
        secret-key: N/A  # configure gateway public key
      - header: X-ER-App-Token
        secret-key: default

feign:
  hystrix:
    enabled: true

management:
  security:
    enabled: false
security:
  basic:
    enabled: false
#  user:
#    name: root
#    password: root
#  iam:
#    enabled: true
#    sso:
#      host: http://192.168.16.253:8081/iam 
#      enabled: true
#  oauth2:
#    client:
#      client-id: GM7Krl1OfXLv
#      client-secret: 6oZRnLwYIFTcHnSj3hxKR768FacEz3kRsU4yTmXwWACddyZY
#      access-token-uri: ${ ${security.iam.sso.host}/oa}/oauth/token
#      user-authorization-uri: ${ ${security.iam.sso.host}/oa}/oauth/authorize
#      scope: default
#    resource:
#      jwt:
#        key-value: non-prod-signature
